name = "idkaboutbytes/rectutils"
version = "1.0.1"
description = "Rectutils package for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/rectutils"
includes = ["pesde.toml", "README.md", "CHANGELOG.md", "default.project.json", "src/**/*.luau"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies]
Loader = { repo = "idkaboutbytes/loader", rev = "v1.2.2" }
